dist: trusty
language: node_js
services: docker
sudo: required
env:
  global:
  - CRATE_NAME=LiveSplitOne
  - ENCRYPTION_LABEL: 341f345e5c8f
matrix:
  include:
  - env: TARGET=asmjs-unknown-emscripten
    rust: nightly
before_install: set -e
install:
- sh ci/install.sh
- source ~/.cargo/env || true
script:
- bash ci/script.sh
after_script: set +e
cache:
  directories:
    - $HOME/.cargo
    - $TRAVIS_BUILD_DIR/livesplit-core/target
before_cache:
- chmod -R a+r $HOME/.cargo
notifications:
  email:
    on_success: never

node_js:
  - "6"

# Temporary fix for emscripten
group: deprecated-2017Q2
